### ISSUE TITLE
Remove redundant read call before creation

### ISSUE THREAD

**Issue by jotompki** [aws-cloudformation/aws-cloudformation-resource-providers-ses#34]
No reason to check if a ConfigurationSet exists before creating it. We can just remove this and rely on the create call throwing a ConfigurationSetAlreadyExists

https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-ses/blame/master/aws-ses-configurationset/src/main/java/software/amazon/ses/configurationset/CreateHandler.java#L68-L73

**Comment by rjlohan** [comment]
Does that exception happen? If so, agree. If not, the READ is needed to fulfil the CREATE contract.

**Comment by jotompki** [comment]
```
$ aws ses create-configuration-set --configuration-set "Name=Name"
$ aws ses create-configuration-set --configuration-set "Name=Name"

An error occurred (ConfigurationSetAlreadyExists) when calling the CreateConfigurationSet operation: Configuration set <Name> already exists.
```

**Comment by wbingli** [comment]
Most service resource existence check during create operation provides strong consistent  guarantee.  It's also a preferred way to use.    Doing READ for resource existence cannot ensure the consistency for following CREATE.
